exclude: '^(data/)'
default_language_version:
    python: python3.8
repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
    - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21-2
  hooks:
    - id: isort
