[tool.black]
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.ipynb_checkpoints
    | \.pytest_cache
    | _build
    | buck-out
    | build
    | dist
  )/
  | artifact/
  |bamboo/
  |configs/
  |data/
  |documents/
  |kubernetes/
  |pipeline/
  |tickets/
  |tf_logs/

)
'''

[tool.isort]
exclude = '^(data/)'
